In [2]:
import numpy as np

In [5]:
b = [1,2,3,"cat", 5.55]
a = np.array([1,2,3,4,5])

print(f"List: {b}")
print(f"Arrays: {a}")

List: [1, 2, 3, 'cat', 5.55]
Arrays: [1 2 3 4 5]


In [7]:
#addition
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print("sum: ", a+b)

#dot product
print("Product: ", np.dot(a,b))

sum:  [ 6  8 10 12 14]
Product:  115


Numpy arrays are mush faster than Python lists when it comes to mathematical operations

Because numpy arrays are implemented in 'C', Python lists are implemented in Python

In [8]:
#Determining the memory usage of both
import sys
a = [1,2,3,4,5,6,7]
b = np.array([1,2,3,4,5,6,7])
print("List: ", sys.getsizeof(a))
print("Array: ", b.nbytes)

List:  120
Array:  28


Array creation function
1. np.zeros
2. np.ones
3. np.empty
4. np.arange
5. np.linspace
6. np.logspace
7. np.full()
8. np.eye()

In [15]:
# converting python list to NumPy array
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

#converting tuple to Numpy array
tuple1 = (1,2,3,4,5)
array = np.array(tuple1)
print(array)

# creating 2d array
# a lsit of list
array2 = np.array([[5,7], [6,8]])
print(array2)
print("__________")

array3 = np.array([[[1,2], [5,8]], [[4,5], [6,7]]])
print(array3)

[1 2 3 4 5]
[1 2 3 4 5]
[[5 7]
 [6 8]]
__________
[[[1 2]
  [5 8]]

 [[4 5]
  [6 7]]]


In [20]:
# creating multi-dimensional array creation function

# 1d array
# np.arange   np.linspace
array4 = np.arange(2,10)
print(array4)

array5 = np.arange(2,10, 0.5, dtype=float)
print(array5)

[2 3 4 5 6 7 8 9]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [22]:
array6 = np.linspace(2,10)
print(array6)
print("**********")

array7 = np.linspace(2, 10, num=5)
print(array7)

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
**********
[ 2.  4.  6.  8. 10.]


In [23]:
# 2d array
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [25]:
#3d array
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.empty([2,3], dtype=int)

array([[1791981024,        721,          0],
       [         0,     131074,          0]])

Basic Operations of Arrays

In [36]:
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)
print(a, b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

[1 2 3 4 5] [ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]


In [38]:
#matrix multiplication
c = np.array([[1,2], [4,6]])
d = np.array([[3,4], [6,6]])

print(np.dot(c,d))

[[15 16]
 [48 52]]


In [39]:
#Trignometric function
trig = np.array([0,15,30,60])

#converting degree values to radius
trig1 = np.deg2rad(trig)
print("Sin: ", np.sin(trig1))
print("Cos: ", np.cos(trig1))

Sin:  [0.         0.25881905 0.5        0.8660254 ]
Cos:  [1.         0.96592583 0.8660254  0.5       ]


In [40]:
#Logarithmic functions
a = 32
print(np.log(a))
print(np.log10(a))

3.4657359027997265
1.505149978319906


In [41]:
#Bitwise operations
bit1 = np.array([1,2,3,4,5], dtype=np.uint8)
bit2 = np.array([2,3,4,5,6], dtype=np.uint8)

print("Bitwise and: ", np.bitwise_and(bit1, bit2))
print("Bitwise or: ", np.bitwise_or(bit1, bit2))


Bitwise and:  [0 2 0 4 4]
Bitwise or:  [3 3 7 5 7]


In [42]:
##Comparision Operatios
print(a==b)
print(a>b)
print(a<b)
print(a!=b)
print(a>=b)
print(a<=b)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [46]:
##Aggregation Functions

a = np.arange(1,10)

#Sum
print(np.sum(a))
#Mean
print(np.mean(a))
#Median
print(np.median(a))
#standard deviation
print(np.std(a))
#Varience
print(np.var(a))
#Maximum
print(np.amax(a))
#Minimum
print(np.amin(a))

45
5.0
5.0
2.581988897471611
6.666666666666667
9
1


In [48]:
##Sorting operations
print(np.sort(b))

[ 6  7  8  9 10]


In [49]:
#desending order
print(np.sort(b)[::-1])

[10  9  8  7  6]


Indexing and Slicing

In [50]:
import numpy as np 

a = np.array([3,5,2,89,45,44,32,67])

In [54]:
a[3]

89

In [55]:
a[-3]

44

In [56]:
a[-8]

3

In [58]:
b = np.array([[2,3], [5,6]])
b

array([[2, 3],
       [5, 6]])

In [63]:
b[1][1]  , b[1][0]

(6, 5)

In [62]:
b[0], b[1]

(array([2, 3]), array([5, 6]))

In [66]:
#boolean indexing
x = np.array([1,2,3,5,1,7,9,7,2,1,3])

x[x!=1] -= 1  #if x is not equal to 1, reduce by 1
x

array([1, 1, 2, 4, 1, 6, 8, 6, 1, 1, 2])

Slicing

In [67]:
c = np.arange(1, 10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
c[2:8]

array([3, 4, 5, 6, 7, 8])