Reshaping, Splitting & Stacking fo Arrays

In [1]:
import numpy as np

In [6]:
#Reshaping
a = np.array([[1,2,4,6,7], [4,2,6,8,8]])
a.shape

(2, 5)

In [8]:
a.reshape(5,2)

array([[1, 2],
       [4, 6],
       [7, 4],
       [2, 6],
       [8, 8]])

In [12]:
#Splitting
b, c = np.split(a, 2, axis=0)
print(b)
print(c)

[[1 2 4 6 7]]
[[4 2 6 8 8]]


In [13]:
#Stacking (combining two or more array as a single array)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.vstack((a,b))
d = np.hstack((a,b))
print(c)
print(d)


[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [16]:
#Concate
a = np.array([[2,3,4,7], [4,5,6,7]])
b = np.ones((1,4))

c = np.concatenate((a,b), axis=0)
print(c)

d = np.concatenate((a,b), axis=None)
print(d)

[[2. 3. 4. 7.]
 [4. 5. 6. 7.]
 [1. 1. 1. 1.]]
[2. 3. 4. 7. 4. 5. 6. 7. 1. 1. 1. 1.]


In [18]:
#transpose
a = np.array([[1,2,3,], [5,6,7]])
print(a)

b = np.transpose(a)
print(b)

[[1 2 3]
 [5 6 7]]
[[1 5]
 [2 6]
 [3 7]]


In [20]:
b.T

array([[1, 2, 3],
       [5, 6, 7]])

In [21]:
#ndim, nsize, nshape
a.size

6

In [22]:
a.ndim

2

In [24]:
a.shape

(2, 3)

### Broadcasting
1. Broadcasting is a feature in the NumPy lib in Python that allows for arithmetic operations between arrays of different shapes.
2. Broadcasting solves the problem of compatibility in shape between arrays of different dimensions during arithmetic operations.
3. The smaller array is broadcasted across the larger array so that they have compatible shapes.
4. Broadcasting provides a mean of vectorizing array operations so that looping occurs in C instead of Python.

In [25]:
import numpy as np

In [26]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2], [4,6]])

arr = arr1+arr2
print(arr)

ValueError: operands could not be broadcast together with shapes (6,) (2,2) 

In [28]:
#multiply a scalar to a bigger array -- simple broadcasting

a = np.arange(1,7)
b = 2.0
c = a*b
c

array([ 2.,  4.,  6.,  8., 10., 12.])

General Rules of Broadcasting

1. Axes must be aligned
2. If  the arrays have different numbers of dimensions, the shape of the smaller array will be padded with ones oon the left

In [30]:
a = np.array([1,2,3])
b = np.array([[4], [5], [6]])
c = a+b
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

2. The size in each dimension mush either be equal or one of them must be one
2. If the size in particular dimension does not match and neither is one, then a ValueError will be raised

In [31]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9]])
c = a+b 
c

array([[ 8, 10, 12],
       [11, 13, 15]])

In [32]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([7,8,9])
c = a+b 
c

array([[ 8, 10, 12],
       [11, 13, 15]])

In [35]:
a = np.array([[1,2,3], [4,5,6]])   #size in this array is different (2,3)
b = np.array([[7,8], [4,5]] )      #size in this array is different (2,2)
c = a+b 
c

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [36]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7], [4]] )
c = a+b 
c

array([[ 8,  9, 10],
       [ 8,  9, 10]])

3. Broadcasting occurs along the first dimension.
4. If an array has size 1 in perticular dimension and the other array has a size greater than 1, then the smaller array's shape is broadcast to match the larger array

In [40]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1,2,3] )
c = a+b 
c

array([[2, 4, 6],
       [5, 7, 9]])

Limitations:
1. Broadcasting only works for arrays with a lower dimension to an array with a higher dimensions, not vice versa.
2. Broadcasting can only add or multiply a scalar to an array, it cannot perform other operations such as division or subtraction.
3. Broadcasting is a performance-critical operation and can lead to slow computation if performed incorrectly, such as wen broadcasting arrays wit a alarge number of elements.